# Icinga 2 Docker image | (c) 2020 Icinga GmbH | GPLv2+

name: Icinga 2 Docker image
inputs:
  dockerhub-token:
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout HEAD
      uses: actions/checkout@v3

    - name: QEMU
      shell: bash
      run: sudo apt-get install -y qemu-user-static binfmt-support

    - shell: bash
      run: docker buildx create --use

    - if: inputs.dockerhub-token != ''
      name: docker login
      env:
        PW: ${{ inputs.dockerhub-token }}
      shell: bash
      run: docker login -u icingaadmin --password-stdin <<<"$PW"

    - if: github.event_name == 'release'
      name: Build and push tag
      shell: bash
      run: '${{ github.action_path }}/build.bash' . all

    - if: github.event_name == 'push'
      name: Build and push branch
      shell: bash
      run: '${{ github.action_path }}/build.bash' . push '${{ github.ref_name }}'

    - if: github.event_name != 'release' && github.event_name != 'push'
      name: Build PR
      shell: bash
      run: '${{ github.action_path }}/build.bash' . all
